// pipeline
// {
//     agent none
//     stages
//     {
//      stage('build')
//         {
//         steps{
//             echo "this is build stage"
//              }
//         }
//
//         stage('test')
//         {
//             steps{
//
//             }
//         }
//     }
// }

pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Rajikehinde/MyStudent.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t mystudent-app .'
            }
        }

        stage('Run App') {
            steps {
                sh 'docker run -d -p 8081:8081 --name mystudent mystudent-app'
            }
        }
    }
}
