pipeline
{
    agent any
    tools {
      maven 'Maven 3.9'
    }
    parameters {
      choice choices: ['dev', 'prod'], name: 'select_environment'
    }

    environment{
        NAME = "kerahn"
    }

    stages
    {
     stage('build')
        {
        steps{
            script{
                file = load "script.groovy"
                file.hello()
            }
            sh 'mvn clean package -DskipTests=true'
             }

//         post {
//           success {
//                 archiveArtifacts artifacts: '**/target/*.jar'
//                 }
//             }
        }
        stage('test')
            {
                parallel
                {
                    stage('test A')
                    {
                        agent {label 'DevServer'}
                        steps
                        {
                            echo " This is test A"
                            sh "mvn test"
                        }
                    }
                    stage('test B')
                    {
                        agent {label 'DevServer'}
                        steps
                        {
                            echo " This is test B"
                            sh "mvn test"
                        }
                    }
                }
                post {
                   success {
                        dir("webapp/target/")
                        {
                            stash name: "maven-build", includes: "*.jar"
                        }
//                        archiveArtifacts artifacts: '**/target/*.jar'
                           }
                     }
            }
            stage(deploy_dev)
            {
                when {expression {params.select_environment == 'dev'}
                beforeAgent true
                }
                agent {label 'DevServer'}
                steps
                {
                    dir("/var/www/html")
                    {
                        unstash "maven-build"
                    }
                    sh """
                    cd /var/www/html/
                    jar -xvf webapp.jar
                    """
                }
            }

            stage(deploy_prod)
            {
                when {expression {params.select_environment == 'prod'}
                beforeAgent true
                }
                agent {label 'ProdServer'}
                steps
                {
                    timeout(time:5, unit: 'DAYS'){
                        input message: 'Deployment approved?'
                    }
                    dir("/var/www/html")
                    {
                       unstash "maven-build"
                    }
                    sh """
                    cd /var/www/html/
                    jar -xvf webapp.jar
                    """
                }
            }
    }
}


